name: Build LLVM 
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize disk space
        uses: theoparis/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - name: Check disk spaceo
        run: |
          echo "Free space:"
          df -h
          echo "Mounts:"
          mount
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check out LLVM 
        uses: actions/checkout@v4
        with:
          repository: "llvm/llvm-project"
          path: llvm-project 
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Configure LLVM
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v5.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          generateReleaseNotes: true
          artifacts: "install"

