name: Build LLVM 
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize disk space
        uses: theoparis/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - name: Check disk spaceo
        run: |
          echo "Free space:"
          df -h
          echo "Mounts:"
          mount
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check out LLVM 
        uses: actions/checkout@v4
        with:
          repository: "llvm/llvm-project"
          path: llvm-project 
      - run: sudo apt update && sudo apt install ninja-build zstd libarchive-tools ccache
      - name: Configure LLVM
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Create Release
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
      - name: Compress artifactss
        run: |
          bsdtar --zstd --options "zstd:threads=4,zstd:compression-level=22" -cvf llvm.tar.zst -C install .
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./llvm.tar.zst
