name: Build LLVM (PR)
on: 
  workflow_dispatch:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize disk space
        uses: theoparis/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-docker-images: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - name: Check disk spaceo
        run: |
          echo "Free space:"
          df -h
          echo "Mounts:"
          mount
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check out LLVM 
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: "llvm/llvm-project"
          path: llvm-project 
      - run: sudo apt update && sudo apt install ninja-build zstd libarchive-tools ccache
      - name: Configure LLVM
        run: |
          chmod +x build.sh
          ./build.sh
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        name: Upload Tempoary Artifacts
        with:
          name: llvm-pr
          path: install
          retention-days: 7

